twist_mux:
  ros__parameters:
    topics:
      teleop_twist_keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 100
      nav2:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10